### ISSUE TITLE
Permission Services

### ISSUE THREAD

**Issue by pumbas600** [pumbas600/Halpbot#6]
The permission service is meant to allow for you to add permissions / restrict who can use commands by linking string-based permissions such as `guild.admin` with actual roles in discord.

The database should look like this:

![image](https://cdn.discordapp.com/attachments/529203773042851863/926261051576680499/Fu16CMT1VXAAAAAElFTkSuQmCC.png)

Note that while the vast majority of permissions will be guild-specific, some - such as `halpbot.owner.bot` are not and would have to manually keep track of users with this permission. (Maybe exclude this for now)

### TODO:

- [ ] Setup DerbyFileRemote for permission database
- [ ] Setup HH service to connect to db
- [ ] Integrate db into PermissionService
- [ ] Add options to configuration file
- [ ] Integrate with JDA Permissions
